comment out nli tasks for now

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -377,102 +377,104 @@ jobs:
       - name: run notebook
         run: jupyter nbconvert --to notebook --execute examples/named_entity_recognition/Named_Entity_Recognition_with_Tensorflow_and_🔭_Galileo.ipynb
 
-  nli-pytorch:
-    runs-on: ubuntu-latest
-    needs: paths-filter
-    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && needs.paths-filter.outputs.nli-pytorch == 'true') }}
-    timeout-minutes: 30
-    strategy:
-      matrix:
-        python-version: ["3.8"]
-      fail-fast: false
+  # NOTE: these tests are disabled as they are non-trivial to fix and nli is not a priority for us at the moment
+  # NOTE: we will re-enable these tests when we have more bandwidth to fix them and there's more customer feedback
+  # nli-pytorch:
+  #   runs-on: ubuntu-latest
+  #   needs: paths-filter
+  #   if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && needs.paths-filter.outputs.nli-pytorch == 'true') }}
+  #   timeout-minutes: 30
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.8"]
+  #     fail-fast: false
 
-    permissions:
-      contents: "read"
-      id-token: "write"
+  #   permissions:
+  #     contents: "read"
+  #     id-token: "write"
 
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
 
-      - name: set up python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: "pip"
-          cache-dependency-path: "requirements-ci.txt"
+  #     - name: set up python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: "pip"
+  #         cache-dependency-path: "requirements-ci.txt"
 
-      - name: install dependencies
-        run: pip install -r requirements-ci.txt
+  #     - name: install dependencies
+  #       run: pip install -r requirements-ci.txt
 
-      - name: run notebook
-        run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/Natural_Language_Inference_using_Pytorch_and_🔭_Galileo.ipynb
+  #     - name: run notebook
+  #       run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/Natural_Language_Inference_using_Pytorch_and_🔭_Galileo.ipynb
 
-  nli-pytorch-simple:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      matrix:
-        python-version: ["3.8"]
-      fail-fast: false
+  # nli-pytorch-simple:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.8"]
+  #     fail-fast: false
 
-    permissions:
-      contents: "read"
-      id-token: "write"
+  #   permissions:
+  #     contents: "read"
+  #     id-token: "write"
 
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
 
-      - name: set up python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: "pip"
-          cache-dependency-path: "requirements-ci.txt"
+  #     - name: set up python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: "pip"
+  #         cache-dependency-path: "requirements-ci.txt"
 
-      - name: install dependencies
-        run: pip install -r requirements-ci.txt
+  #     - name: install dependencies
+  #       run: pip install -r requirements-ci.txt
 
-      - name: run notebook
-        run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/Natural_Language_Inference_using_Pytorch_and_🔭_Galileo_Simple.ipynb
+  #     - name: run notebook
+  #       run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/Natural_Language_Inference_using_Pytorch_and_🔭_Galileo_Simple.ipynb
 
-  nli-tensorflow:
-    runs-on: ubuntu-latest
-    needs: paths-filter
-    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && needs.paths-filter.outputs.nli-tensorflow == 'true') }}
-    timeout-minutes: 30
-    strategy:
-      matrix:
-        python-version: ["3.8"]
-      fail-fast: false
+  # nli-tensorflow:
+  #   runs-on: ubuntu-latest
+  #   needs: paths-filter
+  #   if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && needs.paths-filter.outputs.nli-tensorflow == 'true') }}
+  #   timeout-minutes: 30
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.8"]
+  #     fail-fast: false
 
-    permissions:
-      contents: "read"
-      id-token: "write"
+  #   permissions:
+  #     contents: "read"
+  #     id-token: "write"
 
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
 
-      - name: set up python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: "pip"
-          cache-dependency-path: "requirements-ci.txt"
+  #     - name: set up python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: "pip"
+  #         cache-dependency-path: "requirements-ci.txt"
 
-      - name: install dependencies
-        run: pip install -r requirements-ci.txt
+  #     - name: install dependencies
+  #       run: pip install -r requirements-ci.txt
 
-      - name: run notebook
-        run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/Natural_Language_Inference_using_TensorFlow_and_🔭_Galileo.ipynb
+  #     - name: run notebook
+  #       run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/Natural_Language_Inference_using_TensorFlow_and_🔭_Galileo.ipynb
 
   tc-hf-trainer:
     runs-on: ubuntu-latest
@@ -701,7 +703,6 @@ jobs:
       - name: run notebook
         run: jupyter nbconvert --debug --to notebook --execute examples/object_detection/Object_Detection_using_Ultralytics_and_🔭_Galileo.ipynb
 
-
   send-slack-notification:
     runs-on: ubuntu-latest
     if: github.event_name != 'pull_request'
@@ -714,7 +715,6 @@ jobs:
         ner-spacy,
         ner-spacy-inf,
         ner-tensorflow,
-        nli-tensorflow,
         tc-hf-trainer,
         tc-keras,
         tc-pytorch,
